config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "aggregator#index"

  get "/feed.rss", to: "aggregator#index", format: "rss", as: "rubyland_rss"

  get "/titles", to: "aggregator#index", as: :titles_only, defaults: { titles_only: true }

  get "/about", to: "aggregator#about", as: :about

  resources :sources, controller: :feed
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :feed

  validates :entry_id, presence: true
end

app/models/feed.rb
class Feed < ApplicationRecord
  enum status: %w{suggested approved rejected suspended}.collect { |a| [a,a] }.to_h

  enum fetch_status: %w{not_yet_attempted ok not_modified error}.collect { |a| [a,a] }.to_h,  
    _prefix: 'fetch'
  # note, enum above will creates scopes Feed.fetch_error etc

  scope :fetch_success, -> { where(fetch_status: %w{ok not_modified}) }

  scope :with_latest_entry, -> { select("feeds.*, entries.datetime AS latest_entry_datetime, entries.title AS latest_entry_title, entries.url AS latest_entry_url").left_outer_joins(:entries).where('entries.datetime is null OR entries.datetime = (SELECT MAX(entries.datetime) FROM entries WHERE entries.feed_id = feeds.id)') }

  has_many :entries, dependent: :destroy

  validates :feed_url, presence: true

  def fetch_success?
    fetch_ok? || fetch_not_modified?
  end

  def mark_success(status = :ok)
    # no idea why self is needed here??
    self.last_fetch_at = Time.now
    self.fetch_status = status
    self.fetch_error_info = nil
  end

  def mark_failed(exception: nil)
    self.last_fetch_at = Time.now
    self.fetch_status = :error
    self.fetch_error_info = serialize_error_info(exception)
  end



  protected

  def serialize_error_info(exception)
    {
      class_name: exception.class.name,
      message: exception.message,
      backtrace: exception.backtrace
    }
  end

end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  validates_length_of :password, minimum: 8, except: -> { skip_password_validation? }

  def admin?
    role == "admin"
  end
end

app/controllers/aggregator_controller.rb
class AggregatorController < ApplicationController
  def index
    if Rails.env.production? || ENV['HTTP_CACHING']
      fresh_when etag: etag
    end
  end

  protected

  def entries
    # start_of_day keeps our condition from changing every second,
    # for cacheability.
    earliest_time = Time.now.utc.beginning_of_day - 3.months
    @entries ||= Entry.includes(:feed).order("datetime desc, created_at desc").where("updated_at > ?", earliest_time).limit(110)
  end
  helper_method :entries

  def titles_only?
    !! params[:titles_only]
  end
  helper_method :titles_only?

  def view_cache_key
    # cache so the view doesn't have to look it up again, although
    # I think entries.cache_key would prob be cached anyway, but not certain.
    @view_cache_key ||= [request.format, titles_only?, entries]
  end
  helper_method :view_cache_key

  def etag
    # add the heroku SOURCE_VERSION to our etag, so we get
    # a new etag on every deploy. We could try to access the way
    # Rails does template dependency fingerprinting, but it misses
    # a lot of things, and involves kind of reverse engineering Rails.
    # This is pretty decent.
    [ENV['SOURCE_VERSION']] + view_cache_key
  end

  def absolute_http_url?(str)
    Addressable::URI.parse(str).try { |u| %w{http https}.include?(u.scheme) }
  rescue Addressable::URI::InvalidURIError
    return false
  end
  helper_method :absolute_http_url?

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception

  # just a simple thing to keep google and such away before
  # we've released.
  if ENV['DEMO_PASSWORD']
    before_action :protected_demo_authentication
  end

  protected

  def protected_demo_authentication
    auth = authenticate_with_http_basic do |u, p|
      p == ENV['DEMO_PASSWORD']
    end
    if !auth
      request_http_basic_authentication
    end
  end

end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  def index
    if Rails.env.production? || ENV['HTTP_CACHING']
      fresh_when etag: etag
    end
  end

  protected

  # Can't do a count on our 'with_latest_entry' join, so...
  def base_feeds
    @base_feeds ||= Feed.order("UPPER(feeds.title)")
  end

  def feed_count
    @feed_count ||= base_feeds.count
  end
  helper_method :feed_count

  def feeds
    @feeds ||= base_feeds.with_latest_entry
  end
  helper_method :feeds

  def view_cache_key
    # cache so the view doesn't have to look it up again, although
    # I think entries.cache_key would prob be cached anyway, but not certain.
    @view_cache_key ||= [request.format.to_s, Feed.order(updated_at: :desc).first.updated_at.utc.rfc3339]
  end
  helper_method :view_cache_key

  def etag
    # add the heroku SOURCE_VERSION to our etag, so we get
    # a new etag on every deploy. We could try to access the way
    # Rails does template dependency fingerprinting, but it misses
    # a lot of things, and involves kind of reverse engineering Rails.
    # This is pretty decent.
    [ENV['SOURCE_VERSION']] + view_cache_key
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def date_is_utc_beginning_of_day?(date)
    date.beginning_of_day == date
  end
end

app/helpers/feed_helper.rb
module FeedHelper

  def class_for_feed_status(feed)
    if feed.fetch_success?
      ''
    else
      'text-danger'
    end
  end

  def rss_body(entry)
    label = "Originally appeared on ".html_safe + link_to(entry.feed.title, entry.feed.url) + ".".html_safe
    content_tag(:p, label, class: "rubyland-attribution", data: { rubyland_attribution: true }) +
      (entry.prepared_body || '').html_safe
  end

end

app/views/aggregator/about.html.slim
  - content_for :title,  "Rubyland"
  - content_for :controls do
    ul
      li
        <a href="https://github.com/jrochkind/rubyland"><i class="fa fa-github"></i> Github</a>
      li = link_to "https://twitter.com/rubylandnews" do
        i.fa.fa-twitter
        |  Twitter
      li = link_to rubyland_rss_path do
        i.fa.fa-rss
        |  RSS Feed


  .about
    h2
    p
      i First deployed November 2016, more features planned. Your feedback is welcome!
    p
      | A project by Jonathan Rochkind.
      '
      = link_to "http://github.com/jrochkind", class: 'shortlink' do
        i.fa.fa-external-link
        |  Github
      = link_to "http://bibwild.wordpress.com", class: 'shortlink'
        i.fa.fa-external-link
        |  Blog
    p
      | There have been several ruby and Rails feed aggregators in the past, but
      |   none were still functional and maintained.
      |  I missed them, and I thought a good aggregator could help increase cohesion of
      |  the ruby community. So I built this as a spare-time side project.
    p
      | I intend <em>Rubyland</em> as
      |  a more contemporary iteration of 'planet'-style aggregation, which I think
      |  still serves a use despite social aggregator sites.

    p The source code of <em>Rubyland</em> is open source, and available #{link_to 'on Github', 'https://github.com/jrochkind/rubyland'}

    h2 Sponsors
    .sponsors
      p I develop and operate Rubyland to provide a service to the community, in my spare time to my income-generating work. I don't do it as a profit-making activity.

      p Rubyland is pretty cheap to run (currently under $30/month), but I'm just paying that out of my pocket to support the project, so if anyone is interested in a modest sponsorship of rubyland.news, the community support would really mean a lot to me, and help keep Rubyland from costing me money. Consider it "public radio style" support.

      p <a href="https://github.com/sponsors/jrochkind">Please consider sponsoring me via Github Sponsors.</a>

      p Rubyland.news does not do and has never done any content paid-placement or sponsored "guest posts" or reviews. Please do not contact me offering those standard (often non-disclosed) paid-placement or standard marketing parternships. Any content decisions on rubyland.news are always my own editorial judgement to serve the community.

    h2 Infrastructure
    p <em>Rubyland</em> runs on:
    ul
      li one heroku 'hobby' dyno, with free heroku postgres Hobby Dev. Rubyland can get away with only one small dyno, because it's mostly cached content. (A free dyno would have worked, but the paid hobby dyno gives us SSL on our custom hostname. Thanks to our sponsor for covering the cost.)
      li namecheap domain registrar
      li cloudflare free DNS
      li mailgun free account for MX server for @rubyland.news, and SMTP for admin alerts from app. (registered directly at mailgun.com gives you somewhat higher limits/features than heroku add-on free tier)

    h2 Suggest a Source
    p
      | A form to suggest new sources is planned, but not yet available. Please feel free to contact
      |  me at <a href="mailto:jonathan@rubyland.news">jonathan@rubyland.news</a>.

    h2 Feedback and Contact
    p
      | Please do contact me with any feedback, questions, concerns, problems, suggestions, or thanks, at <a href="mailto:jonathan@rubyland.news">jonathan@rubyland.news</a>.

app/views/aggregator/index.html.slim
- content_for :controls do
  ul
    - if titles_only?
      li = link_to root_path do
        i.fa.fa-align-left
        |  Summaries
    - else
      li = link_to titles_only_path do
        i.fa.fa-list-ul
        |  Titles Only
    li = link_to "https://twitter.com/rubylandnews" do
      i.fa.fa-twitter
      span.long-label  Twitter
      span.short-label  TWTR
    li = link_to rubyland_rss_path do
      i.fa.fa-rss
      span.long-label  RSS Feed
      span.short-label  RSS

.entries class=('titles-only' if titles_only?)
  - cache(view_cache_key) do
    - entries.each do |entry|
      .entry
        .entry-head
          .entry-pre-header
            span.entry-header-source
              = link_to entry.feed.title, entry.feed.url || entry.url
              | &nbsp;
              span.entry-feed-url
                = link_to entry.feed.feed_url do
                  i.fa.fa-rss
            span.entry-datetime data-time=entry.datetime.utc.iso8601 data-time-calendar-only=date_is_utc_beginning_of_day?(entry.datetime)
              =< l entry.datetime.to_date, format: :long
          h2.entry-title
            = link_to_if entry.url, entry.title, entry.url
        - unless titles_only?
          .entry-body
            = raw entry.prepared_body
        - if entry.url
          div.entry-footer
            - unless titles_only?
              = link_to "Read more at #{entry.feed.title}", entry.url, class: 'entry-footer-source'
            .links
              a.link-reddit data-link-reddit=entry.url href="https://www.reddit.com/r/ruby/#{CGI.escape entry.url}"
                i.fa.fa-reddit
                |  Reddit

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-32x32.png' %>" sizes="32x32">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-16x16.png' %>" sizes="16x16">
<link rel="manifest" href="<%= asset_path 'favicon/manifest.json' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#b71c1c">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/feed/index.html.slim
- content_for :title, "Sources"

- content_for :controls do
  ul
    li = "#{feed_count} feeds"
    li
      = link_to sources_path(format: :opml) do
        i.fa.fa-file-code-o
        |  OPML


- cache(view_cache_key) do
  a.btn.btn-outline-primary href='#' Suggest a Source
  .sources
    - feeds.each do |feed|
      .source
        h2 name="id_#{feed.id}"
          = link_to_if feed.url, feed.title || "[missing]", feed.url, name: "link_id#{feed.id}"
        .source-body
          ul.list-unstyled.links
            li
              i.fa.fa-link.bullet-icon
              '
              span.link-cell
                = link_to_if feed.url, feed.url, feed.url do
                  span.tag.tag-danger missing
            li
              i.fa.fa-rss.bullet-icon
              '
              = link_to feed.feed_url, feed.feed_url
          h3.subhead Last Fetch
          .last-fetch-info
            .last-fetch-info-cell.status
              span class=class_for_feed_status(feed)
                = feed.fetch_status
            .last-fetch-info-cell.datetime-ago
              - if feed.last_fetch_at
                = time_ago_in_words(feed.last_fetch_at)
                |  ago
            .last-fetch-info-cell.datetime
              = feed.last_fetch_at.to_s
          -if feed.latest_entry_title
            h3.subhead Latest Entry
            .latest-entry
              span.latest-entry-datetime
                = l feed.latest_entry_datetime.to_date, format: :long
              span.latest-entry-title
                = link_to_if feed.latest_entry_url, feed.latest_entry_title, feed.latest_entry_url

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="dns-prefetch" href="//fonts.googleapis.com/">
    <%= render 'application/favicon' %>

    <%= auto_discovery_link_tag :rss, rubyland_rss_url, title: "Rubyland Aggregated RSS" %>

    <title>Rubyland</title>
    <%= csrf_meta_tags %>

    <%= javascript_include_tag 'application', defer: true %>
    <%= stylesheet_link_tag '//fonts.googleapis.com/css?family=Fira+Sans:light,regular,medium,bold|Anonymous+Pro', media: 'all' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <div class="header">
      <div class="header-brand">
        <h1><%= link_to 'Rubyland', root_url %></h1>
        <div class="header-subtitle">
          news, opinion, tutorials, about <a href="https://www.ruby-lang.org/">ruby</a>, aggregated
        </div>
      </div>
      <div class="header-nav">
        <%= link_to "Sources", sources_path, class: "header-nav-item" %>
        <%= link_to "About", about_path, class: "header-nav-item" %>
      </div>
    </div>

    <% if content_for?(:title) %>
      <h1 class="page-title"><%= content_for :title %></h1>
    <% end %>

    <div class="wrapper">
      <!-- one line so we can trigger empty css when absent -->
      <div class="controls"><%= content_for :controls %></div>
      <div class="main-column">
        <%= yield %>
      </div>
    </div>







  </body>
</html>